name: Check Code Formatting ğŸ› ï¸
on:
  workflow_call:
jobs:
  clang-format:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: clang-format check ğŸ‰
        id: clang-format
        uses: ./.github/actions/run-clang-format
        with:
          failCondition: error

  gersemi:
    runs-on: self-hosted
    needs: clang-format
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: gersemi Check ğŸ›ï¸
        id: gersemi
        uses: ./.github/actions/run-gersemi
        with:
          failCondition: error
